[package]
edition = "2021"
name = "profiles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles"

[dependencies]
hdk_crud = { version = "0.5.6", features = ["no_example"] }
chrono = "0.4.19"
hdk = "0.0.142"
holo_hash = {version = "=0.0.30", features = ["encoding", "fixturators"]}
profiles_integrity = { path = "../profiles_integrity" }
paste = "*"
serde = "*"
thiserror = "1"
