[package]
name = "profiles"
version = "0.0.1"
edition = "2021"

[lib]
name = "profiles"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk_crud = "0.5.5"
holo_hash = { version = "=0.0.19", features = ["encoding", "fixturators"] }
hdk = "0.0.122"
paste = "*"
serde = "*"
thiserror = "1"
chrono = "0.4.19"
