[package]
edition = "2021"
name = "projects"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "projects"

[dependencies]
# hdk_crud = "0.5.5"
projects_integrity = { path = "../projects_integrity" }
hdk = "0.0.142"
hdk_crud = {git = "https://github.com/lightningrodlabs/hdk_crud.git", rev = "bb7bd99", features = ["no_example"]}
holo_hash = {version = "=0.0.30", features = ["encoding", "fixturators"]}
paste = "*"
# use whatever serde hdk uses
chrono = "0.4.19"
serde = "*"
thiserror = "1"
