[package]
edition = "2021"
name = "projects"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "projects"

[dependencies]
# hdk_crud = "0.5.5"
hdk = "0.0.134"
hdk_crud = {git = "https://github.com/lightningrodlabs/hdk_crud.git", branch = "update-to-hdk-134"}
holo_hash = {version = "=0.0.26", features = ["encoding", "fixturators"]}
paste = "*"
# use whatever serde hdk uses
chrono = "0.4.19"
serde = "*"
thiserror = "1"
