
name: Cargo tests

on: [ push, pull_request ]

jobs:
  cargo_test:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v2
     - uses: actions-rs/toolchain@v1
       with:
         toolchain: 1.56
         target: wasm32-unknown-unknown

     - uses: actions-rs/cargo@v1
       with:
         command: check

     - run: rustup component list --installed
     - run: rustup show

     - run: ./scripts/dna-test.sh
