name: Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  build-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install nodejs dependencies
        run: |
          npm run web-install
        shell: bash
      - name: run unit tests
        run: |
          npm run web-test
        shell: bash
