name: Unit Tests

on:
  push:
    branches:
      - '*'

jobs:
  unit-test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Build zod-models dependency
        run: |
          yarn workspace zod-models build
        shell: bash
      - name: run unit tests
        run: |
          yarn workspace acorn-ui test
        shell: bash
